### ISSUE TITLE
Installation failed Can't load generated lib/buildcustomize.pl

### ISSUE THREAD

**Issue by soulsurfer51** [luntergroup/octopus#148]
Installation of Octopus 0.0.7 is crashing at the same point on Linux Centos 7. Any idea how to solve it?

```
==> Installing htslib dependency: perl
==> ./Configure -des -Dprefix=/home/rico/octopus/build/brew/Cellar/perl/5.32.1 -Dprivlib=/home/rico/octopus/build/brew/Cellar/perl/5.32.1/lib/perl5/5.32.1 -Dsitelib=/home/ric
==> make
Last 15 lines from /home/rico/.cache/Homebrew/Logs/perl/02.make:
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/rico/octopus/build/brew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC pp_sort.c
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/rico/octopus/build/brew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC caretx.c
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/rico/octopus/build/brew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC dquote.c
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/rico/octopus/build/brew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC time64.c
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/rico/octopus/build/brew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC miniperlmain.c
rm -f pod/perl5321delta.pod
/usr/bin/ln -s perldelta.pod pod/perl5321delta.pod
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/rico/octopus/build/brew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC op.c
cc -fstack-protector-strong -L/usr/local/lib -o miniperl \
    opmini.o perlmini.o  gv.o toke.o perly.o pad.o regcomp.o dump.o util.o mg.o reentr.o mro_core.o keywords.o hv.o av.o run.o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o doop.o doio.o regexec.o utf8.o taint.o deb.o universal.o globals.o perlio.o perlapi.o numeric.o mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o  miniperlmain.o  -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc 
LD_LIBRARY_PATH=/tmp/perl-20210203-12209-1owgxvx/perl-5.32.1 ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
LD_LIBRARY_PATH=/tmp/perl-20210203-12209-1owgxvx/perl-5.32.1 ./miniperl -Ilib -f write_buildcustomize.pl
do "lib/buildcustomize.pl" failed, '.' is no longer in @INC; did you mean do "./lib/buildcustomize.pl"? at write_buildcustomize.pl line 106.
Can't load generated lib/buildcustomize.pl:  at write_buildcustomize.pl line 117.
make: *** [lib/buildcustomize.pl] Error 13

READ THIS: https://docs.brew.sh/Troubleshooting

Traceback (most recent call last):
  File "install.py", line 510, in <module>
    main(args)
  File "install.py", line 421, in main
    ret = call(["cmake3"] + cmake_options + [".."])
  File "/usr/lib64/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'cmake3'
```

**Comment by dancooke** [comment]
What are your installation commands?

**Comment by soulsurfer51** [comment]
I use the command line: `octopus/scripts/install.py --dependencies --forests`
I am under Linux Centos 7

**Comment by dancooke** [comment]
Unfortunately, Hombrew - the package manger that the installation script uses for dependencies - has recently made some big changes that has broken GCC on CentOS7. I'm trying to find a workaround for this.
