### ISSUE TITLE
Error building custom error profile with script profiler.py

### ISSUE THREAD

**Issue by johnemajor** [luntergroup/octopus#65]
**Describe the bug**
I ran octopus with the flag 'data-profile' set, and produced a *.data.profile file which looks like this:

`period,periods,motif,reference_count,reference_span,indel_length,polymorphisms,errors,reads
0,0,N,1,1245993027,1,104731,1022277,177937789
0,0,N,1,1245993027,2,34317,419616,177937789
0,0,N,1,1245993027,3,10775,252426,177937789
0,0,N,1,1245993027,4,14593,174630,177937789
`

When I run ```python profiler.py -P ./NA24385.octopus.data.profile -O ./model``` 

the following error is thrown after about 1min:
`
(wgspy3) ubuntu@ai-parabricks:~/octopus/scripts$ python profiler.py -P ~/d5/results/jem_octo_crap1/24385/jem_x2/NA24385/NA24385.octopus.data.profile -O a
Traceback (most recent call last):
  File "profiler.py", line 154, in <module>
    main(parsed)
  File "profiler.py", line 139, in main
    profiles_df = read_indel_error_profile_and_summary(options.profile)
  File "profiler.py", line 60, in read_indel_error_profile_and_summary
    return read_indel_error_profile_summaries(read_indel_profile(csv))
  File "profiler.py", line 57, in read_indel_error_profile_summaries
    return make_error_summaries(indel_profile_df)
  File "profiler.py", line 48, in make_error_summaries
    result['period'] = aggregate_errors(indel_profile_df)
  File "profiler.py", line 25, in aggregate_errors
    errors_df = errors_df.groupby(aggregators).aggregate(aggregation_functions, axis='columns')
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/generic.py", line 7632, in groupby
    observed=observed, **kwargs)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 2110, in groupby
    return klass(obj, by, **kwds)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 360, in __init__
    mutated=self.mutated)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 572, in _get_grouper
    obj._check_label_or_level_ambiguity(gpr)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/generic.py", line 1655, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'period' is both an index level and a column label, which is ambiguous.

`

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  result['phred_error'] = result.apply(lambda row: rate_to_phred(row['error_rate']), axis=1)
Traceback (most recent call last):
  File "profiler.py", line 154, in <module>
    main(parsed)
  File "profiler.py", line 140, in main
    error_model = make_octopus_indel_error_model(profiles_df)
  File "profiler.py", line 123, in make_octopus_indel_error_model
    model = smooth_empirical_model(make_empirical_indel_error_model_helper(profile_df, pattern))
  File "profiler.py", line 111, in smooth_empirical_model
    max_penalty = max_lt(open_model[2:], 50)
  File "profiler.py", line 106, in max_lt
    return max(v for v in seq if v < val)
ValueError: max() arg is an empty sequence
`

**Desktop (please complete the following information):**
I'm running on a 96core big memory AWS instance.
Octopus version is: octopus v0.6.3-beta (HEAD fd981298)
numpy==1.16.3
python 3.7.3
**Additional context**

**Comment by dancooke** [comment]
I should have resolved the Pandas errors in 4d3a1951c035eb0a17b1da9349a933dd0566b31b and 00208d6e008659cb98afa5a7ad9cd456274028bc (on develop branch), although this doesn't explain why the data profile only contains `N` motifs. Is this the entire profile or did you just show the first three lines?
